[[pages]]
path = "/"
screenshotTimestamp = "2026-04-15T19:15:42Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/4a86f79d-e987-4ca4-afaf-c570d8ddf2c6/7fe113a5-4b36-4d9b-9bf1-0f7193f687a5/PVGXFfq"
